### ISSUE TITLE
Merging HAL TEI and Grobid TEI for header information

### ISSUE THREAD

**Issue by Aazhar** [anHALytics/anHALytics-core#16]
1) if abstract in HAL TEI is missing, take the one of Grobid and update the TEI header
2) if keywords in HAL TEI are missing, take the ones of Grobid and update the TEI header
3) For authors in HAL TEI, add corresponding Grobid affiliations in the author/laboratory/department//institution entity representation (no update of TEI document)

**Comment by lfoppiano** [comment]
4) if date is 0000 or absent, take the one from the submission date or GROBID date (see discussion on 0001-12-31 problem in LOCATION table)

see example
`SELECT * FROM DOCUMENT_IDENTIFIER as di JOIN DOCUMENT AS d ON d.docID = di.docID JOIN PUBLICATION AS p ON p.docID = d.docID WHERE ID = 'hal-00143297';`
