### ISSUE TITLE
add identifier table in ORGANISATION

### ISSUE THREAD

**Issue by lfoppiano** [anHALytics/anHALytics-core#38]
In order to be in line with the rest of the database identifier management (the identifier might not be present at the time the data is arriving, and, there might be multiple identifier for the same entity). 
Would be good to add an additional table called ORGANISATION_IDENTIFIER, that allows storing identifiers in a separate way than the entity itself (in this case organisation) for an example look at the DOCUMENT_IDENTIFIER.

Additionally the uri column into DOCUMENT table seems a duplicate or, not used correctly, as it is storing the hal-id (which is already stored somewhere else ;))

**Comment by Aazhar** [comment]
👍
