### ISSUE TITLE
ID types are not consistent between *_IDENTIFIERS table

### ISSUE THREAD

**Issue by lfoppiano** [anHALytics/anhalytics-core#56]
The type inside the PERSON_IDENTIFIER table are: 

author: 
```
SELECT DISTINCT type FROM PERSON_IDENTIFIER;

halAuthorId
idHal
ORCID
ResearcherId
IdRef
arXiv
VIAF
ISNI
```

while organisation: 
```
SELECT DISTINCT type FROM ORGANISATION_IDENTIFIER;

halId
ISNI
IdRef
RNSR
IdUnivLorraine
```
What's the difference between idHal and halAuthorID? 
Why in this table is called halId, while in the person is called idHal?

In the DOCUMENT_IDENTIFIER table they are called even differently (hal): 

```
hal
arxiv
doi
irstea
pubmed
oatao
sciencespo
prodinra
bibcode
ensam
ird
pubmedcentral
```

in SERIAL_IDENTIFIER the column is not used.

**Comment by lfoppiano** [comment]
To summarise: 

**Author**
- `idHal`: is the unique ID given to authors by author itself to deduplicate themselves, e.g. Laurent Romary has `idHal` laurentromary over all the appeareances in the DB
- `halAuthorId`: is the id generated for each entry of the person in the database

**Organisation**
 - `halId`: is the identifier provided to organisation and is unique (?) 

What I've understood so far is that authors are deduplicated manually by themselves, while organisation are deduplicated manually by HAL. Is this correct? 

@lfarhi could you please validate if these information are correct?

**Comment by lfoppiano** [comment]
I've just found that some people might have used the idHal to group the whole team...
```
"label","blockID","structID","forename","middlename","surname","fullname","email","title","phone","url"
"author","403","tyrex-equipe","C?cile","","Roisin","C?cile Roisin","","","",""
"author","403","tyrex-equipe","Nabil","","Laya?da","Nabil Laya?da","","","",""
"author","403","tyrex-equipe","Pierre","","Genev?s","Pierre Genev?s","","","",""
"author","403","tyrex-equipe","Nils","","Gesbert","Nils Gesbert","","","",""
```

https://aurehal.archives-ouvertes.fr/author/browse?critere=idHal_i:%229678%22

Any explanation on this?

**Comment by lfarhi** [comment]
Hello Luca,
Here some answers.

**For authors**
- **idHal** : is the unique ID of an author. There is 2 values for this id : a numeric one given by HAL that you should not use and a text one given by the author. For example, Laurent romary : numeric id is 197539 and text id is laurentromary (https://aurehal.archives-ouvertes.fr/author/read/id/197539)
- **halAuthorId** : is called an "author form". It is not generated for each entry of the person in the database. But a new author form is generated when it does not exit already (first name, last name, other name, email, url, organism).
- Author forms are deduplicated manually by administrators but they create themselves their idHal.
-  an idHal for a team is not a the good way and should not occur. 

**For organism**
- halId: is the identifier provided to organization and is unique : YES
- organisms are deduplicated by administrators

**Comment by lfoppiano** [comment]
@lfarhi Thanks! That's clear. What should we do with the `tyrex-equipe`? In my training data I've created manually 5 different idHal. Shouldn't be fixed in HAL as well?

**Comment by lfoppiano** [comment]
@lfarhi I've found another author that have inconsistent data (see last two entries where the name/lastname are swapped): 

<img width="958" alt="screen shot 2016-12-29 at 10 49 37" src="https://cloud.githubusercontent.com/assets/15426/21541186/b36924a4-cdb4-11e6-9e39-2026d67fe5f0.png">

What should we do with these cases? Shall this be corrected directly in HAL? Where can I report them?

**Comment by lfarhi** [comment]
@lfoppiano : we'll see with Alain what to do with these cases and correct them.

**Comment by lfoppiano** [comment]
OK, thanks @lfarhi. In the meantime where should I report eventual other issues?  
I think this issue should be closed as it clarified the initial question ;-)

**Comment by lfoppiano** [comment]
@lfarhi I have a further question about the [comment on 28th of December](https://github.com/anHALytics/anhalytics-core/issues/56#issuecomment-269517009). 

For `organisation`, you said they are disambiguated by administrators. I've understood that many take care of their affiliation themself. 

Do you have a list of organisations manually disambiguated by `INRIA` administrators?

**Comment by lfarhi** [comment]
hello,
Inria structure are normally disambiguated by INRIA administrators. Here is the list : https://aurehal.archives-ouvertes.fr/structure/browse/critere/parentName_s%3AInria%2A+AND+type_s%3Aresearchteam/category/%2A/solR/1/page/2/nbResultPerPage/50/tri/valid
or with API : https://api.archives-ouvertes.fr/ref/structure/?q=parentName_s:Inria*%20AND%20type_s:researchteam&wt=xml-tei (see https://api.archives-ouvertes.fr/docs/ref/resource/structure for API documentation).
bye
Laurence

**Comment by kermitt2** [comment]
@lfarhi hi Laurence! Would you also know by chance other organisations (like INRA?) where the local administrators take care of manually disambiguting affiliations like it is done at Inria? 
The goal here is to find "clean" training/evaluation data manually disambiguated because supervised training is very sensitive to the quality of training data.

**Comment by lfarhi** [comment]
Salut Patrice, 
en voici quelques unes : 
Laurence Douilly pour Télécom Bretagne https://aurehal.archives-ouvertes.fr/structure/read/id/301262 
Marie-Annick Guillemer pour l'Irmar https://aurehal.archives-ouvertes.fr/structure/read/id/75 
upmc https://aurehal.archives-ouvertes.fr/structure/read/id/93591 
AgroParisTech https://aurehal.archives-ouvertes.fr/structure/read/id/148117 
Gipsa-lab https://aurehal.archives-ouvertes.fr/structure/read/id/24470 

Tu en veux d'autres ? 
A+ 
Laurence

**Comment by lfoppiano** [comment]
@lfarhi mercí. Je vais regarder si c'est sufficent.

**Comment by lfoppiano** [comment]
@lfarhi I'm having a look at the INRIA structures. 
In the comment [here](https://github.com/lfarhi) why are you using `AND type_s=researchteam"`? Why are you not including `laboratory` and `departments` as well? 

Looking at the results of the query `https://api.archives-ouvertes.fr/ref/structure/?q=parentName_s:Inria*%20AND%20type_s:researchteam%20AND%20valid_s:VALID&wt=xml-tei` it seems that anyway `type_s=researchteam` is not really considered: 
<img width="865" alt="screen shot 2017-02-17 at 09 56 57" src="https://cloud.githubusercontent.com/assets/15426/23058952/a086243a-f4f7-11e6-8c5e-b6de0f257cce.png">

it this normal? 

Thanks!
Luca

**Comment by lfoppiano** [comment]
Additionally, is it normal to have duplicated entries? INRIA, is repeated several times: 
<img width="868" alt="screen shot 2017-02-17 at 10 06 09" src="https://cloud.githubusercontent.com/assets/15426/23059280/08ecb1dc-f4f9-11e6-8aff-590aa0696b7d.png">

As the mother institution should not happear in the result lists, why is it listed? is it because of the references within the TEI?

**Comment by lfarhi** [comment]
Actually, with the request : https://api.archives-ouvertes.fr/ref/structure/?q=parentName_s:Inria*%20AND%20type_s:researchteam&wt=xml-tei&fl=label_s,type_s&rows=10000 (be careful to add &rows=10000), you have the structures with parent name "Inria*" and type "researchteam" **BUT** also the parent structures of these research teams.
If you use the Solr xml format (wt=xml) : https://api.archives-ouvertes.fr/ref/structure/?q=parentName_s:Inria*%20AND%20type_s:researchteam&wt=xml&fl=docid*,label_s,type_s&rows=1000 you get only the research team structures.

**Comment by lfoppiano** [comment]
OK, but why searching only for `researchteam` and not for `department` and `laboratory`? In this way I won't get `Inria Paris` or `Inria Rhone-Alpes`. isn't it?

**Comment by lfarhi** [comment]
ok, you can search on all the structures and remove "type_s:researchteam"

**Comment by lfoppiano** [comment]
yes, my question is just because I want to understand if you choose to fetch only the research teams for any specific reasons, or was just an example?

**Comment by lfoppiano** [comment]
I have collected all the records that are manually disambiguated and I reach approximately 400 entries. @lfarhi If you have more examples they would be good as well. 

Thanks

**Comment by lfoppiano** [comment]
@lfarhi j'ai besoin de plus de organisations qui son deduplie manualement. Est-ce que tu pourrais me donner des autres?

**Comment by lfarhi** [comment]
Salut Luca,
Les sous-structures Inria sont dédupliquées : https://aurehal.archives-ouvertes.fr/structure/browse?critere=parentDocid_i:300009&category=*
Ainsi que :
- celles de agroParistech : : https://aurehal.archives-ouvertes.fr/structure/browse?critere=parentDocid_i:148117&category=* 
- celles de l'upmc : https://aurehal.archives-ouvertes.fr/structure/browse?critere=parentDocid_i:93591&category=*
Ca suffit ?
A bientôt
Laurence

**Comment by lfoppiano** [comment]
@lfarhi j'ai deja celles. 

Maintenant je prend: 
 - parentName_s:Inria*: INRIA and sub-structures:
 - parentDocid_i:301262: Télécom Bretagne and sub-structures
 - parentDocid_i:75: Irmar  and sub-structures
 - parentDocid_i:93591: upmc  and sub-structures
 - parentDocid_i:148117: AgroParisTech  and sub-structures
 - parentDocid_i:24470: Gipsa-lab and sub-structures

Tu as des autres?

**Comment by lfarhi** [comment]
En voici d'autres :+1: 
parentDocid_i:303623 : Inserm
parentDocid_i:300027:  Institut Pasteur
parentDocid_i:116256 : Université Toulouse 2
parentDocid_i:222110 : IFSTTAR
parentDocid_i:116205 : Université Paris Nanterre
parentDocid_i:302049 : IRSTEA

**Comment by lfoppiano** [comment]
Merci!  J'ai environ de 600 examples.
