### ISSUE TITLE
Generation of duplicated person names during KB initialisation

### ISSUE THREAD

**Issue by lfoppiano** [anHALytics/anhalytics-core#58]
I'm checking the KB initialisation in order to double-check the data for entity-cooking. I've found some problems on the person name, in particular for `Miguel Ramos` here:

```
2880	2	Miguel Ramos	Miguel		Ramos		2015-03-31	2	2	1194353	halAuthorId	2					
2	2	Miguel Ramos	Miguel		Ramos		2015-12-31	2	2	1194353	halAuthorId	2
```					

Looking at the code I've found two (possible) issues, which I would like to know your opinion: 

1. for person_name the first time the name is inserted, the second time, the [method update](https://github.com/anHALytics/anHALytics-core/blob/master/anhalytics-commons/src/main/java/fr/inria/anhalytics/commons/dao/PersonDAO.java#L194) is updating only when the data in is exactly the same as the data in the database. This assumption works for PERSON_IDENTIFIER but not for PERSON_NAMES. In fact the second entry contains a different lastUpdate_date (is the publication date?) therefore is duplicating the record. 
Two options here: 
  - remove the date field (quick fix - not really clean)
  - check whether the personName exists already for this person (maybe checking the fullname?) and check the lastUpdate_date is not more recent than the database lastUpdate_date. 

2. This is more an observation. When there are two or more operations to be done in sequence, for example inserting person, person_name and person_identifier, I noticed the queries are not put into transactions. If one of them fails, the database might contain inconsistencies. 
Additionally it's not possible to run the code with multiple threads.

**Comment by lfoppiano** [comment]
The reason behind this is because while my last harvesting run I've re-processed some dates/months several time (I didn't want to miss any document). 
I've noticed I have much more data, of which many more duplications, for example: 

```
4701	1059	Laurent Romary	Laurent		Romary		1991-09-16
4704	1059	Laurent Romary	Laurent		Romary		1992-09-04
4698	1059	Laurent Romary	Laurent		Romary		1992-12-31
37768	1059	Laurent Romary	Laurent		Romary		1994-04-07
38152	1059	Laurent Romary	Laurent		Romary		1997-12-31
38239	1059	Laurent Romary	Laurent		Romary		1998-12-31
37864	1059	Laurent Romary	Laurent		Romary		1999-11-30
4028	1059	Laurent Romary	Laurent		Romary		2003-12-31
37567	1059	Laurent Romary	Laurent		Romary		2004-12-31
37526	1059	Laurent Romary	Laurent		Romary		2006-12-31
37520	1059	Laurent Romary	Laurent		Romary		2007-06-30
4527	1059	Laurent Romary	Laurent		Romary		2008-12-31
2017	1059	Laurent Romary	Laurent		Romary		2009-12-31
4022	1059	Laurent Romary	Laurent		Romary		2010-01-18
4042	1059	Laurent Romary	Laurent		Romary		2010-01-31
18169	1059	Laurent Romary	Laurent		Romary		2010-07-31
10056	1059	Laurent Romary	Laurent		Romary		2010-11-13
5053	1059	Laurent Romary	Laurent		Romary		2010-11-19
4024	1059	Laurent Romary	Laurent		Romary		2010-12-31
8581	1059	Laurent Romary	Laurent		Romary		2011-11-30
4878	1059	Laurent Romary	Laurent		Romary		2011-12-31
16312	1059	Laurent Romary	Laurent		Romary		2012-01-13
8613	1059	Laurent Romary	Laurent		Romary		2012-07-30
7902	1059	Laurent Romary	Laurent		Romary		2012-12-31
17566	1059	Laurent Romary	Laurent		Romary		2013-03-31
10999	1059	Laurent Romary	Laurent		Romary		2013-06-25
31145	1059	Laurent Romary	Laurent		Romary		2013-08-22
11008	1059	Laurent Romary	Laurent		Romary		2013-10-01
10994	1059	Laurent Romary	Laurent		Romary		2013-12-31
32697	1059	Laurent Romary	Laurent		Romary		2014-09-08
15758	1059	Laurent Romary	Laurent		Romary		2014-11-14
14002	1059	Laurent Romary	Laurent		Romary		2014-11-30
13503	1059	Laurent Romary	Laurent		Romary		2014-12-12
11472	1059	Laurent Romary	Laurent		Romary		2014-12-31
39328	1059	Laurent Romary	Laurent		Romary		2016-11-30
```

For me there should be one and only one `Laurent Romary` and one and only one possible variation, e.g. `L?aurent Romary` or `laurent romary`, etc, but not more than one.

**Comment by Aazhar** [comment]
@lfoppiano , concerning your first point, removing the date field will make  querying authors names complex.

about the second, a transaction is made for each new document, so the scope of a transaction is not related to the authors metadata or monograph or something else..

**Comment by lfoppiano** [comment]
@Aazhar I've got the second point, but not the first actually. What do you mean with _make the querying authors names complex_ ? What about updating the date with the strategy I've mentioned, instead?

**Comment by lfoppiano** [comment]
outdated, at the end we decided not to do any aggregation, which will be done by entity-cooking on a later stage
