### ISSUE TITLE
Update organisation - logic not clear

### ISSUE THREAD

**Issue by lfoppiano** [anHALytics/anHALytics-core#72]
Hi, I have a doubt about the logic to update the organisations. In the part that is updating the partOF part, there is something I cannot understand. See line [251](https://github.com/anHALytics/anHALytics-core/blob/master/anhalytics-commons/src/main/java/fr/inria/anhalytics/commons/dao/anhalytics/OrganisationDAO.java#L251). 

```
PART_OF existingpart_of = getPartOfIfAlreadyStored(obj, rel.getOrganisation_mother());
if (existingpart_of != null) {

    statement2 = connect.prepareStatement(UPDATE_PART_OF, Statement.RETURN_GENERATED_KEYS);
    if (rel.getFromDate().before(existingpart_of.getFromDate())) {
        existingpart_of.setFromDate(rel.getFromDate());
    } else if (rel.getUntilDate().after(existingpart_of.getUntilDate())) {
        existingpart_of.setUntilDate(rel.getUntilDate());
    }
    statement2.setDate(1, new java.sql.Date(existingpart_of.getFromDate().getTime()));

    statement2.setDate(2, new java.sql.Date(existingpart_of.getUntilDate().getTime()));
    statement2.setLong(3, obj.getOrganisationId());
    statement2.setLong(4, rel.getOrganisation_mother().getOrganisationId());
    int code = statement2.executeUpdate();
    result = true;
    statement2.close();
} else {

    PART_OF existingInversepart_of = getPartOfIfAlreadyStored(rel.getOrganisation_mother(), obj);
    if (existingInversepart_of == null) {
        statement2 = connect.prepareStatement(SQL_INSERT_MOTHERS);

        statement2.setFetchSize(Integer.MIN_VALUE);
        statement2.setLong(1, rel.getOrganisation_mother().getOrganisationId());
        statement2.setLong(2, obj.getOrganisationId());
        if (rel.getFromDate() == null) {
            statement2.setDate(3, new java.sql.Date(00000000L));
        } else {
            statement2.setDate(3, new java.sql.Date(rel.getFromDate().getTime()));
        }
        if (rel.getUntilDate() == null) {
            statement2.setDate(4, new java.sql.Date(00000000L));
        } else {
            statement2.setDate(4, new java.sql.Date(rel.getUntilDate().getTime()));
        }

        int code2 = statement2.executeUpdate();
        statement2.close();
    }
}
```

The first IF check whether the PART_OF exists, if it exists, then is updating it. No problem with that. 
The second part of the if it's weird. If the PART_OF doesn't exists, is checking whether the inverted relationship exists, and if it doesn't it's adding it (the inverted relationship). 

if on the database I have only the organisation ALPAGE without relationships, and I get an update to the same organisation with motherOrganisation INRIA. In this case the code will result in adding a relationship PART_OF with `motherOrganisation = ALPAGE` and `organisationID = Inria`, as it won't find the relationships `motherOrganisation = INRIA` and `organisationID = ALPAGE` 

What do you think?

**Comment by Aazhar** [comment]
Actually the checking was made to ensure that there is no inverted relationship when the organisations were deduplicated based on their names (which was reverted here 1e335ab)

**Comment by lfoppiano** [comment]
It was too long ago that I have opened this issue. I cannot quickly go back and check it. 

Did you test your change to see whether it can work for all the cases? Maybe it's worth it before closing it. ;-)

**Comment by Aazhar** [comment]
it should be part of this commit actually 1e335ab , but since deduplicating using names is not a reliable thing, this check is not needed and following a certain logic an organisation should be either a mother or a child for a given part_of relation
