### ISSUE TITLE
Mismatched between HAL API and anHALytics

### ISSUE THREAD

**Issue by lfoppiano** [anHALytics/anHALytics-core#75]
In the last anHALytics export, I've found the following organisation has two records, both marked as `OLD`.

Query: 
```
SELECT *
FROM ORGANISATION AS o
  LEFT JOIN (SELECT
               ID,
               Type,
               organisationID
             FROM ORGANISATION_IDENTIFIER
             WHERE Type = 'halId') AS oi ON oi.organisationID = o.organisationID
  LEFT JOIN (SELECT DISTINCT
               organisationID,
               name
             FROM ORGANISATION_NAME) AS oo ON o.organisationID = oo.organisationID
  LEFT JOIN (SELECT DISTINCT
               locationID,
               organisationID,
               addressID
             FROM LOCATION) AS l ON l.organisationID = o.organisationID
  LEFT JOIN ADDRESS AS a ON a.addressID = l.addressID
  LEFT JOIN COUNTRY AS c ON c.countryID = a.countryID
WHERE name IS NOT NULL AND oo.organisationID IS NOT NULL
      AND name LIKE "Networks, Graphs and Algorithms";
```
Results: 
```
12098,researchteam,http://www.inria.fr/equipes/gang,OLD,34120,halId,12098,12098,"Networks, Graphs and Algorithms",12119,12098,1,1,,,,,,1,1,FR
12098,researchteam,http://www.inria.fr/equipes/gang,OLD,454653,halId,12098,12098,"Networks, Graphs and Algorithms",12119,12098,1,1,,,,,,1,1,FR
```

However the same structure, it's duplicated in HAL with a `VALID` and `OLD`, as here: 
https://aurehal.archives-ouvertes.fr/structure/browse?critere=Networks%2C+Graphs+and+Algorithms&category=*

**Comment by Aazhar** [comment]
I can't tell what's the issue but I know the status could be updated manually by HAL moderators.

**Comment by lfoppiano** [comment]
In the attempt of normalise the `ORGANISATION` having the same names/IDs, two organisation with different `idHAL`s are merged. 
The organisation (record in the `ORGANISATION` table) is the same (`12098`) and it has two `halID`s instead of having two different organisation with same name and different `halID`s. 

I think the problem is in the `getOrgEntityIfAlreadyStored` because the iteration is on the IDs without specifying which one, both these organisation have the same `RNSR`: 

```
RNSR : 200718314F
RNSR : 200718314F
```

**Comment by Aazhar** [comment]
you mean that the exclusive ID should be only halID ?

**Comment by lfoppiano** [comment]
Actually I don't know. In this case they corrected the duplication by deprecating one of the two organisation, instead of merging them physically. 

Regarding your question, yes, but I'm just assuming so, IMHO there cannot two organisation with the same `halID`.

**Comment by lfoppiano** [comment]
outdated (+ I cannot really remember the issue), lets move foward.
