### ISSUE TITLE
Handler to documents for a bibliographical object

### ISSUE THREAD

**Issue by kermitt2** [anHALytics/anhalytics-core#79]
It would be handy to have an handler class corresponding to the level of the "bibliographical object" (so for instance a HAL entry with all its documents, metadata, annexes, versions, or an ISTEX entry with all its associated resources), from which we could easily get the common TEI and the latest PDF for instance with simple methods. 

Currently we are iterating over various objects in MongoDB via MongoFileManager (which is not only managing file actually), and it is hard to get easily the various resources associated to an entry and to understand how to get them. For instance when getting a TeiFile object from the collection ```metadata_teis_fulltext```, the access method getPdfdocument() is not working and is not returning the BinaryFile. 

A more abstract level of representation for the "bibliographical object" managed by the system would be helpful and would make easier the addition of components and new document sources.

**Comment by Aazhar** [comment]
this was resolved in d81eb57
